/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config dist/server/wrangler.json --include-runtime=false` (hash: a9e94a0096c71b46d44f3da39c9efcbb)
interface __BaseEnv_Env {
	CONTACT_EMAIL: SendEmail;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
