/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config dist/server/wrangler.json --include-runtime=false` (hash: 4a9399a583b7cfd67a79e69bdd235428)
interface __BaseEnv_Env {
	CONTACT_EMAIL: SendEmail;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
